// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Models;

public partial class Annualinterview
{
    public decimal AnnualinterviewId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public decimal? EmployeeId { get; set; }

    public decimal? SatisfactionlevelId { get; set; }

    public decimal? InterviewerId { get; set; }

    public bool? InterviewedEnabled { get; set; }

    public bool? InterviewerEnabled { get; set; }

    public decimal? DelegatedBy { get; set; }

    public virtual ICollection<AnnualInterviewFieldItem> AnnualInterviewFieldItem { get; set; } = new List<AnnualInterviewFieldItem>();

    public virtual ICollection<AnnualinterviewField> AnnualinterviewField { get; set; } = new List<AnnualinterviewField>();

    public virtual ICollection<AnnualinterviewRanking> AnnualinterviewRanking { get; set; } = new List<AnnualinterviewRanking>();

    public virtual Employee DelegatedByNavigation { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<Improvementareas> Improvementareas { get; set; } = new List<Improvementareas>();

    public virtual Employee Interviewer { get; set; }

    public virtual ICollection<StatusTracking> StatusTracking { get; set; } = new List<StatusTracking>();
}