// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Models;

public partial class AnnualinterviewField
{
    public decimal AnnualinterviewId { get; set; }

    public decimal FieldAssignmentId { get; set; }

    public decimal FieldId { get; set; }

    public string TextValue { get; set; }

    public int? SelectValue { get; set; }

    public string PathValue { get; set; }

    public virtual Annualinterview Annualinterview { get; set; }

    public virtual Field Field { get; set; }

    public virtual FieldAssignment FieldAssignment { get; set; }
}