// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Models;

public partial class AnnualInterviewFieldItem
{
    public decimal AnnualinterviewId { get; set; }

    public decimal FieldTypeItemId { get; set; }

    public int? FieldTypeItemValue { get; set; }

    public virtual Annualinterview Annualinterview { get; set; }

    public virtual FieldTypeItem FieldTypeItem { get; set; }
}