// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Models;

public partial class Field
{
    public decimal FieldId { get; set; }

    public string FieldName { get; set; }

    public string Comments { get; set; }

    public decimal? FieldTypeId { get; set; }

    public string FieldTitle { get; set; }

    public virtual ICollection<AnnualinterviewField> AnnualinterviewField { get; set; } = new List<AnnualinterviewField>();

    public virtual FieldType FieldType { get; set; }

    public virtual ICollection<LayoutField> LayoutField { get; set; } = new List<LayoutField>();
}