// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Models;

public partial class FieldTypeItem
{
    public decimal FieldTypeItemId { get; set; }

    public decimal? FieldTypeId { get; set; }

    public string ItemLabel { get; set; }

    public virtual ICollection<AnnualInterviewFieldItem> AnnualInterviewFieldItem { get; set; } = new List<AnnualInterviewFieldItem>();

    public virtual FieldType FieldType { get; set; }
}