// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Models;

public partial class FieldAssignment
{
    public decimal FieldAssignmentId { get; set; }

    public string FieldAssignment1 { get; set; }

    public string Comments { get; set; }

    public virtual ICollection<AnnualinterviewField> AnnualinterviewField { get; set; } = new List<AnnualinterviewField>();
}