// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Models;

public partial class FieldType
{
    public decimal FieldTypeId { get; set; }

    public string FieldType1 { get; set; }

    public int? Columns { get; set; }

    public int? Rows { get; set; }

    public virtual ICollection<Field> Field { get; set; } = new List<Field>();

    public virtual ICollection<FieldTypeItem> FieldTypeItem { get; set; } = new List<FieldTypeItem>();
}