// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Models;

public partial class Improvementarea
{
    public decimal ImprovementareaId { get; set; }

    public string Improvementarea1 { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Improvementareas> Improvementareas { get; set; } = new List<Improvementareas>();
}