// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Models;

public partial class InterviewFields
{
    public decimal? AnnualinterviewId { get; set; }

    public decimal? FieldId { get; set; }
}