// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Models;

public partial class Profile
{
    public decimal ProfileId { get; set; }

    public string Profile1 { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Authorization> Authorization { get; set; } = new List<Authorization>();

    public virtual ICollection<Employee> Employee { get; set; } = new List<Employee>();
}