// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Models;

public partial class StatusTracking
{
    public decimal StatusId { get; set; }

    public decimal AnnualinterviewId { get; set; }

    public decimal? UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string Comments { get; set; }

    public virtual Annualinterview Annualinterview { get; set; }

    public virtual Status Status { get; set; }
}