// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Models;

public partial class User
{
    public string Email { get; set; }

    public string Password { get; set; }

    public DateTime PwdExpiresOn { get; set; }

    public bool IsActive { get; set; }

    public decimal? EmployeeId { get; set; }

    public bool? AdAuthentication { get; set; }

    public virtual Employee Employee { get; set; }
}