USE [SKILLS_DEV]
GO
/****** Object:  Table [dbo].[AGENCY]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AGENCY](
	[AGENCY_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[AGENCY_NAME] [nvarchar](50) NULL,
	[COMMENTS] [nvarchar](1000) NULL,
 CONSTRAINT [PK_ENTITY] PRIMARY KEY CLUSTERED 
(
	[AGENCY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ANNUALINTERVIEW]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ANNUALINTERVIEW](
	[ANNUALINTERVIEW_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[CREATED_ON] [date] NULL,
	[EMPLOYEE_ID] [numeric](18, 0) NULL,
	[SATISFACTIONLEVEL_ID] [numeric](18, 0) NULL,
	[INTERVIEWER_ID] [numeric](18, 0) NULL,
	[INTERVIEWED_ENABLED] [bit] NULL,
	[INTERVIEWER_ENABLED] [bit] NULL,
	[DELEGATED_BY] [numeric](18, 0) NULL,
 CONSTRAINT [PK_ANNUALINTERVIEW] PRIMARY KEY CLUSTERED 
(
	[ANNUALINTERVIEW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ANNUALINTERVIEW_RANKING]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ANNUALINTERVIEW_RANKING](
	[ANNUALINTERVIEW_ID] [numeric](18, 0) NOT NULL,
	[RANKING_CRITERION_ID] [numeric](18, 0) NOT NULL,
	[VALUE] [int] NULL,
 CONSTRAINT [PK_ANNUALINTERVIEW_RANKING1] PRIMARY KEY CLUSTERED 
(
	[ANNUALINTERVIEW_ID] ASC,
	[RANKING_CRITERION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AREA]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AREA](
	[AREA_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[AREA] [nvarchar](50) NULL,
	[COMMENT] [nvarchar](100) NULL,
	[IS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK_AREA] PRIMARY KEY CLUSTERED 
(
	[AREA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AUTHORIZATION]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AUTHORIZATION](
	[PROFILE_ID] [numeric](18, 0) NOT NULL,
	[AREA_ID] [numeric](18, 0) NOT NULL,
	[IS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK_AUTHORIZATION2] PRIMARY KEY CLUSTERED 
(
	[PROFILE_ID] ASC,
	[AREA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHANGE_TRACKING]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHANGE_TRACKING](
	[HISTORY_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[LAYOUT_ID] [numeric](18, 0) NULL,
	[CREATED_BY] [numeric](18, 0) NULL,
	[CREATED_ON] [datetime] NULL,
	[UPDATED_BY] [numeric](18, 0) NULL,
	[UPDATED_ON] [datetime] NULL,
 CONSTRAINT [PK_CHANGE_TRACKING] PRIMARY KEY CLUSTERED 
(
	[HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE](
	[EMPLOYEE_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [nvarchar](50) NOT NULL,
	[LAST_NAME] [nvarchar](50) NOT NULL,
	[PROFILE_ID] [numeric](18, 0) NOT NULL,
	[EMAIL] [nvarchar](50) NOT NULL,
	[ENTRY_DATE] [date] NOT NULL,
	[END_DATE] [date] NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[MANAGER_ID] [numeric](18, 0) NULL,
	[EMPLOYEE_NUMBER] [nvarchar](20) NULL,
	[AGENCY_ID] [numeric](18, 0) NULL,
 CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FIELD]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FIELD](
	[FIELD_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[FIELD_NAME] [nvarchar](100) NULL,
	[COMMENTS] [nvarchar](50) NULL,
	[FIELD_TYPE_ID] [numeric](18, 0) NULL,
	[FIELD_LABEL] [nvarchar](50) NULL,
	[FIELD_VALUE] [nvarchar](2000) NULL,
	[ROWS] [int] NULL,
	[COLUMNS] [int] NULL,
	[WIDTH] [int] NULL,
	[HEIGHT] [int] NULL,
	[LINKED_FIELD_ID] [numeric](18, 0) NULL,
 CONSTRAINT [PK_FIELD] PRIMARY KEY CLUSTERED 
(
	[FIELD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FIELD_ACCESS]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FIELD_ACCESS](
	[FIELD_ID] [numeric](18, 0) NOT NULL,
	[PROFILE_ID] [numeric](18, 0) NOT NULL,
	[CAN_READ] [bit] NULL,
	[CAN_WRITE] [bit] NULL,
 CONSTRAINT [PK_FIELD_ACCESS] PRIMARY KEY CLUSTERED 
(
	[FIELD_ID] ASC,
	[PROFILE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FIELD_TYPE]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FIELD_TYPE](
	[FIELD_TYPE_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[FIELD_TYPE] [nvarchar](50) NULL,
	[COMMENTS] [nvarchar](100) NULL,
 CONSTRAINT [PK_FIELD_TYPE] PRIMARY KEY CLUSTERED 
(
	[FIELD_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FIELD_TYPE_ITEM]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FIELD_TYPE_ITEM](
	[FIELD_TYPE_ITEM_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[FIELD_TYPE_ID] [numeric](18, 0) NULL,
	[ITEM_LABEL] [nvarchar](50) NULL,
 CONSTRAINT [PK_FIELD_TYPE_ITEM1] PRIMARY KEY CLUSTERED 
(
	[FIELD_TYPE_ITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IMPROVEMENTAREA]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IMPROVEMENTAREA](
	[IMPROVEMENTAREA_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[IMPROVEMENTAREA] [nvarchar](50) NULL,
	[DESCRIPTION] [nvarchar](200) NULL,
	[IS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK_IMPROVEMENTAREA] PRIMARY KEY CLUSTERED 
(
	[IMPROVEMENTAREA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IMPROVEMENTAREAS]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IMPROVEMENTAREAS](
	[IMPROVEMENTAREA_ID] [numeric](18, 0) NOT NULL,
	[ANNUALINTERVIEW_ID] [numeric](18, 0) NOT NULL,
	[COMMENTS] [nvarchar](200) NULL,
 CONSTRAINT [PK_IMPROVEMENTAREAS] PRIMARY KEY CLUSTERED 
(
	[IMPROVEMENTAREA_ID] ASC,
	[ANNUALINTERVIEW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LAYOUT]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LAYOUT](
	[LAYOUT_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[COLUMNS] [int] NULL,
	[ROWS] [int] NULL,
	[LAYOUT_NAME] [nvarchar](100) NULL,
	[LAYOUT_PROFILE] [numeric](18, 0) NULL,
	[OTHER_PROPERTIES] [nvarchar](200) NULL,
 CONSTRAINT [PK_LAYOUT] PRIMARY KEY CLUSTERED 
(
	[LAYOUT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LAYOUT_FIELD]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LAYOUT_FIELD](
	[FIELD_ID] [numeric](18, 0) NOT NULL,
	[LAYOUT_ID] [numeric](18, 0) NOT NULL,
	[HORIZONTAL_POSITION] [int] NULL,
	[VERTICAL_POSITION] [int] NULL,
	[WIDTH_PERCENTAGE] [int] NULL,
	[HORIZONTALY_ALIGNED] [bit] NULL,
 CONSTRAINT [PK_LAYOUT_FIELD] PRIMARY KEY CLUSTERED 
(
	[FIELD_ID] ASC,
	[LAYOUT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROFILE]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROFILE](
	[PROFILE_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[PROFILE_NAME] [nchar](20) NULL,
	[DESCRIPTION] [nchar](100) NULL,
	[IS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK_PROFILE] PRIMARY KEY CLUSTERED 
(
	[PROFILE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RANKING_CRITERION]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RANKING_CRITERION](
	[RANKING_CRITERION_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[RANKING_CRITERION] [nvarchar](50) NULL,
	[COEFFICIENT] [int] NULL,
 CONSTRAINT [PK_RANKING_CRITERION] PRIMARY KEY CLUSTERED 
(
	[RANKING_CRITERION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STATUS]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STATUS](
	[STATUS_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[STATUS] [nchar](10) NULL,
	[DESCRIPTION] [nchar](100) NULL,
	[IS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK_STATUS] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STATUS_TRACKING]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STATUS_TRACKING](
	[STATUS_ID] [numeric](18, 0) NOT NULL,
	[ANNUALINTERVIEW_ID] [numeric](18, 0) NOT NULL,
	[UPDATED_BY] [numeric](18, 0) NULL,
	[UPDATED_ON] [datetime] NULL,
	[COMMENTS] [nvarchar](100) NULL,
 CONSTRAINT [PK_STATUS_TRACKING1] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC,
	[ANNUALINTERVIEW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYSTEM_PARAMETER]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYSTEM_PARAMETER](
	[PARAMETER_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[PARAMETER_NAME] [nvarchar](50) NULL,
	[PARAMETER_VALUE] [nvarchar](50) NULL,
 CONSTRAINT [PK_SYSTEM_PARAMETER] PRIMARY KEY CLUSTERED 
(
	[PARAMETER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER]    Script Date: 13/07/2023 03:11:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER](
	[EMAIL] [nvarchar](50) NOT NULL,
	[PASSWORD] [nvarchar](50) NOT NULL,
	[PWD_EXPIRES_ON] [date] NOT NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[EMPLOYEE_ID] [numeric](18, 0) NULL,
	[AD_AUTHENTICATION] [bit] NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ANNUALINTERVIEW]  WITH CHECK ADD  CONSTRAINT [FK_ANNUALINTERVIEW_EMPLOYEE] FOREIGN KEY([EMPLOYEE_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEE_ID])
GO
ALTER TABLE [dbo].[ANNUALINTERVIEW] CHECK CONSTRAINT [FK_ANNUALINTERVIEW_EMPLOYEE]
GO
ALTER TABLE [dbo].[ANNUALINTERVIEW]  WITH CHECK ADD  CONSTRAINT [FK_ANNUALINTERVIEW_EMPLOYEE_INTERVIEWER] FOREIGN KEY([INTERVIEWER_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEE_ID])
GO
ALTER TABLE [dbo].[ANNUALINTERVIEW] CHECK CONSTRAINT [FK_ANNUALINTERVIEW_EMPLOYEE_INTERVIEWER]
GO
ALTER TABLE [dbo].[ANNUALINTERVIEW]  WITH CHECK ADD  CONSTRAINT [FK_ANNUALINTERVIEW_EMPLOYEE1] FOREIGN KEY([DELEGATED_BY])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEE_ID])
GO
ALTER TABLE [dbo].[ANNUALINTERVIEW] CHECK CONSTRAINT [FK_ANNUALINTERVIEW_EMPLOYEE1]
GO
ALTER TABLE [dbo].[ANNUALINTERVIEW_RANKING]  WITH CHECK ADD  CONSTRAINT [FK_ANNUALINTERVIEW_RANKING_ANNUALINTERVIEW] FOREIGN KEY([ANNUALINTERVIEW_ID])
REFERENCES [dbo].[ANNUALINTERVIEW] ([ANNUALINTERVIEW_ID])
GO
ALTER TABLE [dbo].[ANNUALINTERVIEW_RANKING] CHECK CONSTRAINT [FK_ANNUALINTERVIEW_RANKING_ANNUALINTERVIEW]
GO
ALTER TABLE [dbo].[ANNUALINTERVIEW_RANKING]  WITH CHECK ADD  CONSTRAINT [FK_ANNUALINTERVIEW_RANKING_RANKING_CRITERION] FOREIGN KEY([RANKING_CRITERION_ID])
REFERENCES [dbo].[RANKING_CRITERION] ([RANKING_CRITERION_ID])
GO
ALTER TABLE [dbo].[ANNUALINTERVIEW_RANKING] CHECK CONSTRAINT [FK_ANNUALINTERVIEW_RANKING_RANKING_CRITERION]
GO
ALTER TABLE [dbo].[AUTHORIZATION]  WITH CHECK ADD  CONSTRAINT [FK_AUTHORIZATION_AREA] FOREIGN KEY([AREA_ID])
REFERENCES [dbo].[AREA] ([AREA_ID])
GO
ALTER TABLE [dbo].[AUTHORIZATION] CHECK CONSTRAINT [FK_AUTHORIZATION_AREA]
GO
ALTER TABLE [dbo].[AUTHORIZATION]  WITH CHECK ADD  CONSTRAINT [FK_AUTHORIZATION_PROFILE] FOREIGN KEY([PROFILE_ID])
REFERENCES [dbo].[PROFILE] ([PROFILE_ID])
GO
ALTER TABLE [dbo].[AUTHORIZATION] CHECK CONSTRAINT [FK_AUTHORIZATION_PROFILE]
GO
ALTER TABLE [dbo].[CHANGE_TRACKING]  WITH CHECK ADD  CONSTRAINT [FK_CHANGE_TRACKING_LAYOUT] FOREIGN KEY([LAYOUT_ID])
REFERENCES [dbo].[LAYOUT] ([LAYOUT_ID])
GO
ALTER TABLE [dbo].[CHANGE_TRACKING] CHECK CONSTRAINT [FK_CHANGE_TRACKING_LAYOUT]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_ENTITY] FOREIGN KEY([AGENCY_ID])
REFERENCES [dbo].[AGENCY] ([AGENCY_ID])
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_ENTITY]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_PROFILE] FOREIGN KEY([PROFILE_ID])
REFERENCES [dbo].[PROFILE] ([PROFILE_ID])
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_PROFILE]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_MANAGER_EMPLOYEE] FOREIGN KEY([MANAGER_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEE_ID])
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK_MANAGER_EMPLOYEE]
GO
ALTER TABLE [dbo].[FIELD]  WITH CHECK ADD  CONSTRAINT [FK_FIELD_FIELD] FOREIGN KEY([LINKED_FIELD_ID])
REFERENCES [dbo].[FIELD] ([FIELD_ID])
GO
ALTER TABLE [dbo].[FIELD] CHECK CONSTRAINT [FK_FIELD_FIELD]
GO
ALTER TABLE [dbo].[FIELD]  WITH CHECK ADD  CONSTRAINT [FK_FIELD_FIELD_TYPE] FOREIGN KEY([FIELD_TYPE_ID])
REFERENCES [dbo].[FIELD_TYPE] ([FIELD_TYPE_ID])
GO
ALTER TABLE [dbo].[FIELD] CHECK CONSTRAINT [FK_FIELD_FIELD_TYPE]
GO
ALTER TABLE [dbo].[FIELD_ACCESS]  WITH CHECK ADD  CONSTRAINT [FK_FIELD_ACCESS_FIELD] FOREIGN KEY([FIELD_ID])
REFERENCES [dbo].[FIELD] ([FIELD_ID])
GO
ALTER TABLE [dbo].[FIELD_ACCESS] CHECK CONSTRAINT [FK_FIELD_ACCESS_FIELD]
GO
ALTER TABLE [dbo].[IMPROVEMENTAREAS]  WITH CHECK ADD  CONSTRAINT [FK_IMPROVEMENTAREAS_ANNUALINTERVIEW] FOREIGN KEY([ANNUALINTERVIEW_ID])
REFERENCES [dbo].[ANNUALINTERVIEW] ([ANNUALINTERVIEW_ID])
GO
ALTER TABLE [dbo].[IMPROVEMENTAREAS] CHECK CONSTRAINT [FK_IMPROVEMENTAREAS_ANNUALINTERVIEW]
GO
ALTER TABLE [dbo].[IMPROVEMENTAREAS]  WITH CHECK ADD  CONSTRAINT [FK_IMPROVEMENTAREAS_IMPROVEMENTAREA] FOREIGN KEY([IMPROVEMENTAREA_ID])
REFERENCES [dbo].[IMPROVEMENTAREA] ([IMPROVEMENTAREA_ID])
GO
ALTER TABLE [dbo].[IMPROVEMENTAREAS] CHECK CONSTRAINT [FK_IMPROVEMENTAREAS_IMPROVEMENTAREA]
GO
ALTER TABLE [dbo].[LAYOUT_FIELD]  WITH CHECK ADD  CONSTRAINT [FK_LAYOUT_FIELD_FIELD] FOREIGN KEY([FIELD_ID])
REFERENCES [dbo].[FIELD] ([FIELD_ID])
GO
ALTER TABLE [dbo].[LAYOUT_FIELD] CHECK CONSTRAINT [FK_LAYOUT_FIELD_FIELD]
GO
ALTER TABLE [dbo].[LAYOUT_FIELD]  WITH CHECK ADD  CONSTRAINT [FK_LAYOUT_FIELD_LAYOUT] FOREIGN KEY([LAYOUT_ID])
REFERENCES [dbo].[LAYOUT] ([LAYOUT_ID])
GO
ALTER TABLE [dbo].[LAYOUT_FIELD] CHECK CONSTRAINT [FK_LAYOUT_FIELD_LAYOUT]
GO
ALTER TABLE [dbo].[STATUS_TRACKING]  WITH CHECK ADD  CONSTRAINT [FK_STATUS_TRACKING_ANNUALINTERVIEW] FOREIGN KEY([ANNUALINTERVIEW_ID])
REFERENCES [dbo].[ANNUALINTERVIEW] ([ANNUALINTERVIEW_ID])
GO
ALTER TABLE [dbo].[STATUS_TRACKING] CHECK CONSTRAINT [FK_STATUS_TRACKING_ANNUALINTERVIEW]
GO
ALTER TABLE [dbo].[STATUS_TRACKING]  WITH CHECK ADD  CONSTRAINT [FK_STATUS_TRACKING_STATUS] FOREIGN KEY([STATUS_ID])
REFERENCES [dbo].[STATUS] ([STATUS_ID])
GO
ALTER TABLE [dbo].[STATUS_TRACKING] CHECK CONSTRAINT [FK_STATUS_TRACKING_STATUS]
GO
ALTER TABLE [dbo].[USER]  WITH CHECK ADD  CONSTRAINT [FK_USER_EMPLOYEE] FOREIGN KEY([EMPLOYEE_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEE_ID])
GO
ALTER TABLE [dbo].[USER] CHECK CONSTRAINT [FK_USER_EMPLOYEE]
GO
