// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Entities;

public partial class Agency
{
    public decimal AgencyId { get; set; }

    public string AgencyName { get; set; }

    public string Comments { get; set; }

    public virtual ICollection<Employee> Employee { get; set; } = new List<Employee>();
}