// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Entities;

public partial class Area
{
    public decimal AreaId { get; set; }

    public string Area1 { get; set; }

    public string Comment { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Authorization> Authorization { get; set; } = new List<Authorization>();
}