// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Entities;

public partial class Authorization
{
    public decimal ProfileId { get; set; }

    public decimal AreaId { get; set; }

    public bool? IsActive { get; set; }

    public virtual Area Area { get; set; }

    public virtual Profile Profile { get; set; }
}