// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Entities;

public partial class ChangeTracking
{
    public decimal HistoryId { get; set; }

    public decimal? LayoutId { get; set; }

    public decimal? CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public decimal? UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public virtual Layout Layout { get; set; }
}