// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Entities;

public partial class FieldAccess
{
    public decimal FieldId { get; set; }

    public decimal ProfileId { get; set; }

    public bool? CanRead { get; set; }

    public bool? CanWrite { get; set; }

    public virtual Field Field { get; set; }
}