// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Entities;

public partial class Field
{
    public decimal FieldId { get; set; }

    public string FieldName { get; set; }

    public string Comments { get; set; }

    public decimal? FieldTypeId { get; set; }

    public string FieldLabel { get; set; }

    public string FieldValue { get; set; }

    public int? Rows { get; set; }

    public int? Columns { get; set; }

    public int? Width { get; set; }

    public int? Height { get; set; }

    public decimal? LinkedFieldId { get; set; }

    public virtual ICollection<FieldAccess> FieldAccess { get; set; } = new List<FieldAccess>();

    public virtual FieldType FieldType { get; set; }

    public virtual ICollection<Field> InverseLinkedField { get; set; } = new List<Field>();

    public virtual ICollection<LayoutField> LayoutField { get; set; } = new List<LayoutField>();

    public virtual Field LinkedField { get; set; }
}