// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Entities;

public partial class FieldTypeItem
{
    public decimal FieldTypeItemId { get; set; }

    public decimal? FieldTypeId { get; set; }

    public string ItemLabel { get; set; }
}