// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Entities;

public partial class FieldItem
{
    public decimal FieldItemId { get; set; }

    public decimal? FieldId { get; set; }

    public string FieldItemLabel { get; set; }

    public bool? FieldItemHorizontal { get; set; }

    public string Tooltip { get; set; }

    public virtual Field Field { get; set; }
}