// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Entities;

public partial class Improvementareas
{
    public decimal ImprovementareaId { get; set; }

    public decimal AnnualinterviewId { get; set; }

    public string Comments { get; set; }

    public virtual Annualinterview Annualinterview { get; set; }

    public virtual Improvementarea Improvementarea { get; set; }
}