// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Entities;

public partial class LayoutType
{
    public decimal LayoutTypeId { get; set; }

    public string LayoutTypeName { get; set; }

    public string Comments { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Layout> Layout { get; set; } = new List<Layout>();
}