// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skills.Entities.Entities;

public partial class SystemParameter
{
    public decimal ParameterId { get; set; }

    public string ParameterName { get; set; }

    public string ParameterValue { get; set; }
}